# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\Work\Programming\!Distr\regulargrid\tools\ReggridByPolygon\ReggridByPolygon.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_reggridByPolygonDialog(object):
    def setupUi(self, reggridByPolygonDialog):
        reggridByPolygonDialog.setObjectName("reggridByPolygonDialog")
        reggridByPolygonDialog.resize(829, 439)
        self.gridLayout = QtWidgets.QGridLayout(reggridByPolygonDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(reggridByPolygonDialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_2.addWidget(self.comboBox, 0, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setEnabled(True)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 1, 0, 1, 2)
        self.gridLayout.addWidget(self.groupBox, 2, 0, 1, 3)
        self.groupBox_3 = QtWidgets.QGroupBox(reggridByPolygonDialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox.setMaximum(1000.0)
        self.doubleSpinBox.setProperty("value", 50.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_4.addWidget(self.doubleSpinBox, 0, 1, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_2.setMaximum(1000.0)
        self.doubleSpinBox_2.setProperty("value", 10.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout_4.addWidget(self.doubleSpinBox_2, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 3, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox.setMaximum(99999)
        self.spinBox.setProperty("value", 1)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_4.addWidget(self.spinBox, 2, 1, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_2.setMaximum(99999)
        self.spinBox_2.setProperty("value", 1)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_4.addWidget(self.spinBox_2, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 4, 0, 1, 1)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_3.setDecimals(2)
        self.doubleSpinBox_3.setProperty("value", 1.0)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.gridLayout_4.addWidget(self.doubleSpinBox_3, 4, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 3, 0, 1, 3)
        self.progressBar = QtWidgets.QProgressBar(reggridByPolygonDialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 4, 0, 1, 3)
        self.textEdit = QtWidgets.QTextEdit(reggridByPolygonDialog)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 1, 3, 5, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(reggridByPolygonDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 5, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(reggridByPolygonDialog)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 3, 1, 1, QtCore.Qt.AlignRight)
        self.AddButton = QtWidgets.QPushButton(reggridByPolygonDialog)
        self.AddButton.setObjectName("AddButton")
        self.gridLayout.addWidget(self.AddButton, 5, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(reggridByPolygonDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_3.addWidget(self.checkBox_3, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 2, 3)

        self.retranslateUi(reggridByPolygonDialog)
        self.buttonBox.accepted.connect(reggridByPolygonDialog.accept)
        self.buttonBox.rejected.connect(reggridByPolygonDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(reggridByPolygonDialog)

    def retranslateUi(self, reggridByPolygonDialog):
        _translate = QtCore.QCoreApplication.translate
        reggridByPolygonDialog.setWindowTitle(_translate("reggridByPolygonDialog", "Создать регулярную сеть в полигоне"))
        self.groupBox.setTitle(_translate("reggridByPolygonDialog", "Выбор ограничивающего полигона"))
        self.label.setText(_translate("reggridByPolygonDialog", "Выберете слой"))
        self.checkBox.setText(_translate("reggridByPolygonDialog", "Использовать только выделенные полигоны"))
        self.groupBox_3.setTitle(_translate("reggridByPolygonDialog", "Параметры разбиения"))
        self.label_4.setText(_translate("reggridByPolygonDialog", "Расстояние между пикетами"))
        self.label_5.setText(_translate("reggridByPolygonDialog", "Номер первого профиля"))
        self.label_3.setText(_translate("reggridByPolygonDialog", "Расстояние между профилями"))
        self.label_6.setText(_translate("reggridByPolygonDialog", "Номер первого пикета"))
        self.label_7.setText(_translate("reggridByPolygonDialog", "<html><head/><body><p>Добавить в разбиение пикеты, </p><p>выходящие за границы полигона на:</p></body></html>"))
        self.textEdit.setHtml(_translate("reggridByPolygonDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>"))
        self.pushButton.setText(_translate("reggridByPolygonDialog", "Help"))
        self.AddButton.setText(_translate("reggridByPolygonDialog", "Add Points"))
        self.groupBox_2.setTitle(_translate("reggridByPolygonDialog", "Слой для добавления точек"))
        self.lineEdit.setText(_translate("reggridByPolygonDialog", "RegularGrid Layer"))
        self.checkBox_3.setText(_translate("reggridByPolygonDialog", "Удалить все точки со слоя перед созданием"))
        self.label_2.setText(_translate("reggridByPolygonDialog", "Имя слоя"))
