# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\YandexDisk\Work\ProjectsRepositories\20221021_regulargrid\regulargrid3\regulargridabout.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CadToolsAbout(object):
    def setupUi(self, CadToolsAbout):
        CadToolsAbout.setObjectName("CadToolsAbout")
        CadToolsAbout.resize(285, 335)
        self.gridlayout = QtWidgets.QGridLayout(CadToolsAbout)
        self.gridlayout.setObjectName("gridlayout")
        self.txtAbout = QtWidgets.QTextEdit(CadToolsAbout)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtAbout.setPalette(palette)
        self.txtAbout.setAutoFillBackground(True)
        self.txtAbout.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.txtAbout.setFrameShadow(QtWidgets.QFrame.Plain)
        self.txtAbout.setReadOnly(True)
        self.txtAbout.setObjectName("txtAbout")
        self.gridlayout.addWidget(self.txtAbout, 2, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem, 3, 1, 1, 1)
        self.btnHelp = QtWidgets.QPushButton(CadToolsAbout)
        self.btnHelp.setObjectName("btnHelp")
        self.gridlayout.addWidget(self.btnHelp, 4, 0, 1, 1)
        self.btnClose = QtWidgets.QPushButton(CadToolsAbout)
        self.btnClose.setObjectName("btnClose")
        self.gridlayout.addWidget(self.btnClose, 4, 2, 1, 1)
        self.btnWeb = QtWidgets.QPushButton(CadToolsAbout)
        self.btnWeb.setObjectName("btnWeb")
        self.gridlayout.addWidget(self.btnWeb, 4, 1, 1, 1)
        self.lblVersion = QtWidgets.QLabel(CadToolsAbout)
        self.lblVersion.setObjectName("lblVersion")
        self.gridlayout.addWidget(self.lblVersion, 1, 0, 1, 2)
        self.lblTitle = QtWidgets.QLabel(CadToolsAbout)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitle.setFont(font)
        self.lblTitle.setTextFormat(QtCore.Qt.RichText)
        self.lblTitle.setObjectName("lblTitle")
        self.gridlayout.addWidget(self.lblTitle, 0, 0, 1, 2)

        self.retranslateUi(CadToolsAbout)
        self.btnClose.clicked.connect(CadToolsAbout.reject)
        QtCore.QMetaObject.connectSlotsByName(CadToolsAbout)

    def retranslateUi(self, CadToolsAbout):
        _translate = QtCore.QCoreApplication.translate
        CadToolsAbout.setWindowTitle(_translate("CadToolsAbout", "Regular Grid about"))
        self.txtAbout.setHtml(_translate("CadToolsAbout", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans Serif\'; font-size:9pt;\"><br /></p></body></html>"))
        self.btnHelp.setText(_translate("CadToolsAbout", "Help"))
        self.btnClose.setText(_translate("CadToolsAbout", "Close"))
        self.btnWeb.setText(_translate("CadToolsAbout", "Web"))
        self.lblVersion.setText(_translate("CadToolsAbout", "Version x.x-xxxxxx"))
        self.lblTitle.setText(_translate("CadToolsAbout", "Regular Grid"))
