# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\YandexDisk\Work\ProjectsRepositories\20221021_regulargrid\regulargrid3\tools\BindElevation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_bindElevationDialog(object):
    def setupUi(self, bindElevationDialog):
        bindElevationDialog.setObjectName("bindElevationDialog")
        bindElevationDialog.resize(400, 247)
        self.verticalLayout = QtWidgets.QVBoxLayout(bindElevationDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(bindElevationDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.rasterLayer = QtWidgets.QComboBox(bindElevationDialog)
        self.rasterLayer.setObjectName("rasterLayer")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.rasterLayer)
        self.label_6 = QtWidgets.QLabel(bindElevationDialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.rasterBand = QtWidgets.QComboBox(bindElevationDialog)
        self.rasterBand.setMinimumSize(QtCore.QSize(120, 0))
        self.rasterBand.setObjectName("rasterBand")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.rasterBand)
        self.label = QtWidgets.QLabel(bindElevationDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.vectorLayer = QtWidgets.QComboBox(bindElevationDialog)
        self.vectorLayer.setObjectName("vectorLayer")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.vectorLayer)
        self.label_2 = QtWidgets.QLabel(bindElevationDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.destinationField = QtWidgets.QComboBox(bindElevationDialog)
        self.destinationField.setObjectName("destinationField")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.destinationField)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(bindElevationDialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.additionValue = QtWidgets.QDoubleSpinBox(bindElevationDialog)
        self.additionValue.setMinimum(-999.99)
        self.additionValue.setMaximum(999.99)
        self.additionValue.setObjectName("additionValue")
        self.horizontalLayout.addWidget(self.additionValue)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.processOnlyNull = QtWidgets.QCheckBox(bindElevationDialog)
        self.processOnlyNull.setObjectName("processOnlyNull")
        self.verticalLayout.addWidget(self.processOnlyNull)
        self.processOnlySelected = QtWidgets.QCheckBox(bindElevationDialog)
        self.processOnlySelected.setObjectName("processOnlySelected")
        self.verticalLayout.addWidget(self.processOnlySelected)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(bindElevationDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.bindElevationButton = QtWidgets.QPushButton(bindElevationDialog)
        self.bindElevationButton.setObjectName("bindElevationButton")
        self.horizontalLayout_2.addWidget(self.bindElevationButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(bindElevationDialog)
        self.buttonBox.accepted.connect(bindElevationDialog.accept)
        self.buttonBox.rejected.connect(bindElevationDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(bindElevationDialog)

    def retranslateUi(self, bindElevationDialog):
        _translate = QtCore.QCoreApplication.translate
        bindElevationDialog.setWindowTitle(_translate("bindElevationDialog", "Bind Elevation"))
        self.label_4.setText(_translate("bindElevationDialog", "Слой - источник данных"))
        self.label_6.setText(_translate("bindElevationDialog", "Канал"))
        self.label.setText(_translate("bindElevationDialog", "Слой назначения"))
        self.label_2.setText(_translate("bindElevationDialog", "Поле назначения"))
        self.label_5.setText(_translate("bindElevationDialog", "Прибавить к значению"))
        self.processOnlyNull.setText(_translate("bindElevationDialog", "Обрабатывать только объекты, где поле назначения не определено"))
        self.processOnlySelected.setText(_translate("bindElevationDialog", "Обрабатывать только выделенные объекты"))
        self.bindElevationButton.setText(_translate("bindElevationDialog", "Bind"))
