# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\YandexDisk\Work\ProjectsRepositories\20221021_regulargrid\regulargrid3\tools\BindToNewLine.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_bindDialog(object):
    def setupUi(self, bindDialog):
        bindDialog.setObjectName("bindDialog")
        bindDialog.setEnabled(True)
        bindDialog.resize(350, 186)
        self.buttonBox = QtWidgets.QDialogButtonBox(bindDialog)
        self.buttonBox.setGeometry(QtCore.QRect(250, 150, 81, 21))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(bindDialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 331, 131))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 70, 111, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(20, 90, 131, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(160, 70, 161, 51))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 91, 16))
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(20, 40, 131, 22))
        self.comboBox.setObjectName("comboBox")
        self.bindButton = QtWidgets.QPushButton(bindDialog)
        self.bindButton.setGeometry(QtCore.QRect(170, 150, 75, 21))
        self.bindButton.setObjectName("bindButton")

        self.retranslateUi(bindDialog)
        self.buttonBox.accepted.connect(bindDialog.accept)
        self.buttonBox.rejected.connect(bindDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(bindDialog)

    def retranslateUi(self, bindDialog):
        _translate = QtCore.QCoreApplication.translate
        bindDialog.setWindowTitle(_translate("bindDialog", "Bind profiles to new Line"))
        self.groupBox.setTitle(_translate("bindDialog", "Bind profiles to current line"))
        self.label.setText(_translate("bindDialog", "Input profiles numbers"))
        self.label_2.setText(_translate("bindDialog", "<html><head/><body><p>e.g. 1,2,3 or 1-4,</p><p>or leave empty for all profiles</p></body></html>"))
        self.label_3.setText(_translate("bindDialog", "Input layer name"))
        self.bindButton.setText(_translate("bindDialog", "Bind"))
