# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\Work\Programming\!Distr\regulargrid\tools\rectangularpoints.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RectangularPoints(object):
    def setupUi(self, RectangularPoints):
        RectangularPoints.setObjectName("RectangularPoints")
        RectangularPoints.resize(437, 209)
        self.gridLayout_2 = QtWidgets.QGridLayout(RectangularPoints)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_5 = QtWidgets.QLabel(RectangularPoints)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.firstPR = QtWidgets.QDoubleSpinBox(RectangularPoints)
        self.firstPR.setDecimals(0)
        self.firstPR.setMaximum(1000.0)
        self.firstPR.setProperty("value", 1.0)
        self.firstPR.setObjectName("firstPR")
        self.horizontalLayout_4.addWidget(self.firstPR)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label_6 = QtWidgets.QLabel(RectangularPoints)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.firstPK = QtWidgets.QDoubleSpinBox(RectangularPoints)
        self.firstPK.setDecimals(0)
        self.firstPK.setMaximum(1000.0)
        self.firstPK.setProperty("value", 1.0)
        self.firstPK.setObjectName("firstPK")
        self.horizontalLayout_4.addWidget(self.firstPK)
        self.chckBoxInvert = QtWidgets.QCheckBox(RectangularPoints)
        self.chckBoxInvert.setObjectName("chckBoxInvert")
        self.horizontalLayout_4.addWidget(self.chckBoxInvert)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblA = QtWidgets.QLabel(RectangularPoints)
        self.lblA.setObjectName("lblA")
        self.horizontalLayout.addWidget(self.lblA)
        self.sboxA = QtWidgets.QDoubleSpinBox(RectangularPoints)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sboxA.sizePolicy().hasHeightForWidth())
        self.sboxA.setSizePolicy(sizePolicy)
        self.sboxA.setObjectName("sboxA")
        self.horizontalLayout.addWidget(self.sboxA)
        self.lblO = QtWidgets.QLabel(RectangularPoints)
        self.lblO.setObjectName("lblO")
        self.horizontalLayout.addWidget(self.lblO)
        self.sboxO = QtWidgets.QDoubleSpinBox(RectangularPoints)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sboxO.sizePolicy().hasHeightForWidth())
        self.sboxO.setSizePolicy(sizePolicy)
        self.sboxO.setObjectName("sboxO")
        self.horizontalLayout.addWidget(self.sboxO)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(RectangularPoints)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.picNum = QtWidgets.QSpinBox(RectangularPoints)
        self.picNum.setMaximum(1000)
        self.picNum.setProperty("value", 50)
        self.picNum.setObjectName("picNum")
        self.horizontalLayout_2.addWidget(self.picNum)
        self.label_3 = QtWidgets.QLabel(RectangularPoints)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.proNum = QtWidgets.QSpinBox(RectangularPoints)
        self.proNum.setMaximum(1000)
        self.proNum.setProperty("value", 5)
        self.proNum.setObjectName("proNum")
        self.horizontalLayout_2.addWidget(self.proNum)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.btnAdd = QtWidgets.QPushButton(RectangularPoints)
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayout_3.addWidget(self.btnAdd)
        self.btnCancel = QtWidgets.QPushButton(RectangularPoints)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_3.addWidget(self.btnCancel)
        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(RectangularPoints)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.dX = QtWidgets.QDoubleSpinBox(RectangularPoints)
        self.dX.setProperty("value", 10.0)
        self.dX.setObjectName("dX")
        self.horizontalLayout_5.addWidget(self.dX)
        self.label_2 = QtWidgets.QLabel(RectangularPoints)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.dY = QtWidgets.QDoubleSpinBox(RectangularPoints)
        self.dY.setProperty("value", 50.0)
        self.dY.setObjectName("dY")
        self.horizontalLayout_5.addWidget(self.dY)
        self.gridLayout.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(RectangularPoints)
        self.groupBox.setObjectName("groupBox")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(10, 20, 191, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(RectangularPoints)
        QtCore.QMetaObject.connectSlotsByName(RectangularPoints)

    def retranslateUi(self, RectangularPoints):
        _translate = QtCore.QCoreApplication.translate
        RectangularPoints.setWindowTitle(_translate("RectangularPoints", "Regular Web"))
        self.label_5.setText(_translate("RectangularPoints", "FirstPR"))
        self.label_6.setText(_translate("RectangularPoints", "FirstPK"))
        self.chckBoxInvert.setText(_translate("RectangularPoints", "Invert starting point"))
        self.lblA.setText(_translate("RectangularPoints", "FirstPicketShift (X):"))
        self.lblO.setText(_translate("RectangularPoints", "FirstPicketShift (Y):"))
        self.label.setText(_translate("RectangularPoints", "PicketNumber(X)"))
        self.label_3.setText(_translate("RectangularPoints", "ProfilesNum(Y)"))
        self.btnAdd.setText(_translate("RectangularPoints", "Add"))
        self.btnCancel.setText(_translate("RectangularPoints", "Cancel"))
        self.label_4.setText(_translate("RectangularPoints", "PicketShift(dX)"))
        self.label_2.setText(_translate("RectangularPoints", "ProfilesShift(dY)"))
        self.groupBox.setTitle(_translate("RectangularPoints", "Имя слоя для добавления точек"))
        self.lineEdit.setText(_translate("RectangularPoints", "RegularGrid Points"))
